services:
  frontend:
    build: ./frontendapp
    ports:
      - "3000:3000"
    networks:
      - mern

  backend:
    build: ./backendapp
    ports:
      - "2032:2032"
    networks:
      - mern

networks:
  mern:
    driver: bridge